### ISSUE TITLE
Error using FolderBrowserDialog.showDialog()

### ISSUE THREAD

**Issue by WillyAguilera** [o3o/dformlib#2]
Sorry my English. I'm new to programming in D.
An Access Violation error occurs when using the method FolderBrowserDialog.showDialog() like the next code below:
private void click(Control c, EventArgs args) {
     FolderBrowserDialog fbd = new FolderBrowserDialog();
     fbd.showDialog();
         label1.text = fbd.selectedPath;
}
It's my error or library's one?.

**Comment by o3o** [comment]
Never mind.. it's better than mine :) .. I will check this night.
